trigger:
  batch: true
  branches:
    include:
    - live

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.deb
    -O '$(Pipeline.Workspace)/hugo_Linux-64bit.deb'
  displayName: Download Hugo Linux x64
- script: sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
  displayName: Install Hugo
- script: hugo 
  displayName: Build site with Hugo 
- task: ArchiveFiles@2
  displayName: Archive built output
  inputs:
    rootFolderOrFile: ./public
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Pipeline.Workspace)/hugo-build.zip
    replaceExistingArchive: true
- publish: $(Pipeline.Workspace)/hugo-build.zip
  artifact: blog
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: 'Daron-Blog'
    appType: webApp
    appName: 'daron-fit'
    package: '$(Pipeline.Workspace)/hugo-build.zip'