baseURL = "https://daron.blog/"
languageCode = "en-us"
title = "Daron Blog"
theme = "noteworthy"
summaryLength = 20
paginate = 5

googleAnalytics = "UA-48954873-4" 

[permalinks]
  posts = "/:year/:title/"

[markup.goldmark.renderer]
    unsafe = true
    
[params]
	math = true
  lightbox = true
	# Blog description at the top of the homepage. Supports markdown.
	description = ""

# Main
twitter = "https://www.twitter.com/daronyondem"
instagram = "https://www.instagram.com/daronyondem"
youtube = "https://www.youtube.com/channel/UC7oYHShBoL7srrAVGMXWK0A/"
linkedin = "https://www.linkedin.com/in/daronyondem/"

# Programming
github = "https://github.com/daronyondem"

[[menu.main]]
	identifier = "about"
	name = "About Me"
	url = "/about"
	weight = 1 

[[menu.main]]
	identifier = "Software"
	name = "Software"
	url = "/tags/software"
	weight = 2 

[[menu.main]]
	identifier = "Speaking"
	name = "Speaking"
	url = "/tags/speaking"
	weight = 3 

[[menu.main]]
	identifier = "Fitness"
	name = "Fitness"
	url = "/tags/fitness"
	weight = 4

[[menu.main]]
	identifier = "others"
	name = "Others"
	url = "/tags/"
	weight = 5

[[menu.main]]
	name = "E-Mail List"
	identifier = "subscribe"
	url = "http://eepurl.com/cU3_0T"
	weight = 6

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true