name: Send Speaking Event Updates to Discord

on:
  push:
    paths:
      - 'content/speaking.md'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install axios

      - name: Extract Table and Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_ANNOUNCMENTS_WEBHOOK_URL }}
        run: node ./.github/workflows/discord-updates.js
